# --- CONFIGURATION & CONSTANTS ---
APP_NAME = "Sektor 2"

DEFAULT_W, DEFAULT_H = 15, 15
DEFAULT_HGT = 0x7F
MAX_SPECIAL_SLOTS = 10

# Height Constraints (+/- 30 from 0x7F)
HGT_MIN = 0x61 # 97
HGT_MAX = 0x9D # 157
EDITOR_HEIGHT_BASE = 30
EDITOR_HEIGHT_MIN = 0
EDITOR_HEIGHT_MAX = 60

GRID_COLOR = "#707070"
MARKER_COLOR = "#FF00FF"
CUSTOM_BORDER_COLOR = "#FF0000" # Bright Red for Custom
TEXT_COLOR = "#00FFFF"
SCROLL_BG = "#00AAAA"
SCROLL_ACTIVE = TEXT_COLOR

HEIGHT_HIGH_COLOR = "#00E5FF"
HEIGHT_BASE_COLOR = "#F2F2F2"
HEIGHT_LOW_COLOR = "#FF7A00"
HEIGHT_PANEL_BG = "#1a1a1a"
HEIGHT_SLIDER_W = 170
HEIGHT_SLIDER_H = 260
HEIGHT_SLIDER_TOP_Y = 24
HEIGHT_SLIDER_BOTTOM_Y = 236
HEIGHT_SLIDER_TRACK_W = 44

DEBUG_RENDER_PERF = False
SHOW_HEIGHT_NUMBERS_OUTSIDE_HGT = False
HGT_NUMBER_MIN_ZOOM = 32

IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg")
TILE_IMAGE_EXTENSIONS = (".png", ".jpg")
GEM_IMAGE_EXTENSIONS = (".png",)

# WORLD SCALE
SECTOR_SIZE = 3072
HALF_SECTOR = SECTOR_SIZE // 2

# Tech Layout
TECH_ITEM_W = 450
TECH_ITEM_H = 24

# Data Structures
FACTIONS = {
    0: ("NEUTRAL", None),
    1: ("RESISTANCE", "#0088FF"),
    2: ("SULGOGAR", "#00FF00"),
    3: ("MYKON", "#FFFFFF"),
    4: ("TAERKASTEN", "#FFFF00"),
    5: ("BLACK SECT", "#555555"),
    6: ("GHORKOV", "#FF0000"),
    7: ("DRONES", "#2A1F3D")
}

FACTION_MAP_COLORS = {
    5: "#555555",
    7: "#2A1F3D",
}

FACTION_MAP_OUTLINES = {
    5: "#D0D0D0",
    7: "#A99BC5",
}

FACTION_TEXT_COLORS = {
    0: "#FFFFFF", 1: "#0088FF", 2: "#00FF00", 3: "#FFFFFF",
    4: "#FFFF00", 5: "#AAAAAA", 6: "#FF4444", 7: "#D0D0D0"
}

HEIGHTS = list(range(256))

PALETTE_ONLY_BUILDING_OVERLAYS = {"beamgate", "gem", "superitem"}
